### ISSUE TITLE
Add flag to change the timeout-period from the default of five seconds.

### ISSUE THREAD

**Issue by Disinterpreter** [skx/rss2hook#2]
I guess this rss-scanner has been frozen work after this error
```
Error fetching https://url/all/rss.xml - Get https://url/all/rss.xml?ann-edition=us: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by skx** [comment]
If an error is found processing a feed the next one will be retried until the whole list of feeds has been processed.  Then it'll sleep for five minutes before trying again.

In short if there is an error it will be logged, but the process should continue to operate and poll the feeds again after five minutes - only skipping the one feed with the error.

Leave it running and you should be able to confirm that.

**Comment by Disinterpreter** [comment]
Ok, probably it's my failure. But could you make a debug mode and range of askwereding (5mins by default) in config file?

**Comment by skx** [comment]
A debug-option isn't a bad idea, but if a timeout happens you'll already see that shown - as you did.

I'm not sure what you're asking about the 5minutes though.  Could you try to explain it more thoroughly?

**Comment by Disinterpreter** [comment]
At the moment we have a hard-codded value of scanning RSS (https://github.com/skx/rss2hook/blob/master/rss2hook.go#L97) Can we setting up it?

**Comment by skx** [comment]
Pull request is welcome; add a new command-line flag, and a new global to hold it.

Otherwise I'll get round to it when I can find time.
